### ISSUE TITLE
Call promise.reject when chrome.runtime.lastError is set

### ISSUE THREAD

**Issue by mwebler** [akiomik/chrome-storage-promise#1]
It would be nice if the promises call the reject function if chrome.runtime.lastError is set. 
This way would be easier to handle errors when using the API.
i.e.:

```
chrome.storage.sync.get(keys, (items) => {
    if(chrome.runtime.lastError) reject();
    else resolve(items);
});
```

**Comment by akiomik** [comment]
Good! I'll try this.

**Comment by akiomik** [comment]
Now I've release `chrome-storage-promise-0.1.0` and support it!
